import type { TaskDefinition } from "../types";

// Module 7 — First Customers. No results promised (P7). No CRM (§3).

export const MODULE_7_TASKS: TaskDefinition[] = [
  {
    id: "7.1",
    moduleId: "first_customers",
    title: "Tell the people who already know you",
    order: 1,
    isRequired: true,
    timeEstimate: "20 minutes",
    whyItMatters:
      "Your first customers almost always come from people who already know you. They just don't know you're doing this yet.",
    whatYouNeed: ["Your phone contacts.", "The details below."],
    doThis:
      "Send a short personal message — not a mass blast — to twenty people you know: what you're doing, where, and your number. Ask them to keep you in mind and pass your name on. Use the message draft from the Description Generator if you want a starting point.",
    primaryCta: { label: "Draft a message", toolId: "descriptions" },
    steps: [
      { text: "Make a list of twenty: family, friends, former coworkers, neighbors, your kid's coach." },
      { text: "Text each one individually. Three sentences: what you do, where, and \"if you know anyone who needs it, here's my number.\"" },
      { text: "Don't ask them to hire you. Ask them to remember you." },
    ],
    troubleshooting: [],
    mistakes: ["One group message to everyone. It reads as spam and gets ignored.", "Being embarrassed to ask. Everyone knows someone who needs a handyman."],
    alternatives: [],
    canonicalFields: [],
    reusesFields: ["displayName", "services", "serviceAreas", "phone", "domain"],
    toolId: "descriptions",
    dependsOn: [],
    sourceLinks: [],
    lastReviewed: "2026-09-13",
    contentStatus: "complete",
  },
  {
    id: "7.2",
    moduleId: "first_customers",
    title: "Post in your local community groups",
    order: 2,
    isRequired: true,
    timeEstimate: "15 minutes",
    whyItMatters:
      "\"Anyone know a good handyman?\" gets asked in every neighborhood group every week. Being the person who's already there, with a real page and real photos, is how you get those jobs.",
    whatYouNeed: ["A Facebook account.", "Your page link, if you made one."],
    doThis:
      "Join two or three local groups for your city and neighboring ones. Read the rules — most allow a business intro post on certain days. Post once: who you are, what you do, where, a photo of your work, your number. Then watch for people asking for recommendations and reply helpfully.",
    primaryCta: { label: "I've joined and posted" },
    steps: [
      { text: "Search Facebook for \"[your city] community\" and \"[your city] neighbors.\" Join two or three active ones." },
      { text: "Read the pinned rules. Post on the allowed day, in the allowed way. Breaking group rules gets you banned from your best lead source." },
      { text: "Reply to recommendation requests with a short, useful answer — not a sales pitch." },
    ],
    troubleshooting: [],
    mistakes: ["Posting ads in groups that forbid them.", "Replying to every post with \"DM me!\" Be a neighbor first."],
    alternatives: [],
    canonicalFields: [],
    reusesFields: ["displayName", "services", "serviceAreas", "phone", "domain"],
    toolId: "descriptions",
    dependsOn: [],
    sourceLinks: [],
    lastReviewed: "2026-09-13",
    contentStatus: "complete",
  },
  {
    id: "7.3",
    moduleId: "first_customers",
    title: "Track your leads and quotes",
    order: 3,
    isRequired: true,
    timeEstimate: "10 minutes to set up",
    whyItMatters:
      "The job you forgot to follow up on is the most expensive one you'll never do. A simple list — not software — is all you need for your first year.",
    whatYouNeed: ["The spreadsheet below, or a notebook."],
    doThis:
      "Download the lead tracker. Every inquiry gets a row: name, what they need, where they found you, and a stage — inquiry, contacted, quoted, won or lost. Update it the same day. Look at it every Friday.",
    primaryCta: { label: "Download the lead tracker", href: "/downloads/lead-tracker.csv" },
    steps: [
      { heading: "The four stages", text: "Inquiry → Contacted → Quoted → Won/Lost. That's the whole pipeline." },
      { heading: "Where did they find you?", text: "Ask every new customer. After twenty rows you'll know exactly where your customers come from — and where to spend your time." },
    ],
    troubleshooting: [],
    mistakes: ["Buying CRM software before you have ten customers."],
    alternatives: [],
    canonicalFields: [],
    reusesFields: [],
    dependsOn: [],
    sourceLinks: [],
    lastReviewed: "2026-09-13",
    contentStatus: "complete",
  },
  {
    id: "7.4",
    moduleId: "first_customers",
    title: "Decide how fast you'll respond",
    order: 4,
    isRequired: true,
    timeEstimate: "5 minutes",
    whyItMatters:
      "Response speed decides more small local jobs than price, reviews, or your website. The customer texts three people; the first one to reply usually gets it.",
    whatYouNeed: ["An honest look at your day."],
    doThis:
      "Pick a response commitment you can keep — \"within two hours during work hours\" is realistic for most solo operators — and write it down. Then set up your phone so you can keep it: a saved reply for when you're on a ladder, and notifications you'll actually see.",
    primaryCta: { label: "Save your commitment below" },
    steps: [
      { text: "Decide the number: 1 hour, 2 hours, same day. Faster is better, but only if you'll actually do it." },
      { text: "Save a holding reply on your phone: \"Got your message — on a job right now, I'll call you back by 4.\" Send it within minutes; call back when you said." },
      { text: "Put the commitment on your website and voicemail so customers know what to expect." },
    ],
    troubleshooting: [],
    mistakes: ["Promising 15 minutes and not delivering. A kept two-hour promise beats a broken fast one."],
    alternatives: [],
    canonicalFields: ["responseCommitment"],
    reusesFields: ["preferredContact"],
    dependsOn: [],
    sourceLinks: [],
    lastReviewed: "2026-09-13",
    contentStatus: "complete",
  },
  {
    id: "7.5",
    moduleId: "first_customers",
    title: "Get your name on your truck and in your pocket",
    order: 5,
    isRequired: false,
    timeEstimate: "30 minutes to order; a few days to arrive",
    whyItMatters:
      "For a mobile trade, your vehicle is your best advertisement — it's parked in front of a customer's house all day where the neighbors can see it. Cards go in every hand you shake.",
    whatYouNeed: ["Your business name, phone, and website (we have them).", "Your colors and logo if you set them."],
    doThis:
      "Order simple vehicle magnets or lettering with three things: your business name, what you do in three words, and your phone number. Order 250 plain business cards with the same three things plus your website. Nothing else — a truck door is read at 30 mph.",
    primaryCta: { label: "I've ordered" },
    steps: [
      { text: "Vehicle: name, trade, phone. Large. Two colors. Magnets if you're not sure about permanence." },
      { text: "Cards: name, trade, phone, website, and your review QR code on the back if you like." },
    ],
    troubleshooting: [],
    mistakes: ["Cramming every service onto the truck. Three words.", "A phone number too small to read from the next lane."],
    alternatives: [],
    canonicalFields: [],
    reusesFields: ["displayName", "phone", "domain"],
    dependsOn: [],
    sourceLinks: [],
    lastReviewed: "2026-09-13",
    contentStatus: "complete",
  },
];
