import type { TaskDefinition } from "../types";

// Module 3 — Your Website. Primary $900 service placements live here (§15.3).
// 3.3 and 3.4 are DRAFT: the one recommended build route is an owner content decision
// (P1 forbids a neutral comparison). Steps are written for outcomes, not clicks (P2).

export const MODULE_3_TASKS: TaskDefinition[] = [
  {
    id: "3.1",
    moduleId: "website",
    title: "What your website actually needs",
    order: 1,
    isRequired: true,
    timeEstimate: "10 minutes of reading",
    whyItMatters:
      "Most people check your site before they call. A weak one quietly costs you the job. But a good local-business site is smaller than you think — one page done well.",
    whatYouNeed: ["Nothing yet. This is the map before the trip."],
    doThis:
      "Read the list below of the eight things a local service website needs. Then decide honestly: build it yourself (10–20 hours over a few weeks) or have GoBeeFound build it for $900 with what you paid for Launch credited. Either answer is fine — just decide.",
    primaryCta: { label: "I've read it — next step" },
    steps: [
      { heading: "1. A clear headline", text: "What you do and where, in one line. \"Mobile auto detailing in Aurora and the south metro.\"" },
      { heading: "2. Your services", text: "The list you made in Module 1, with one line each." },
      { heading: "3. Your service area", text: "The cities you listed. Customers check this before they read anything else." },
      { heading: "4. Why you", text: "Two or three honest reasons, plus your face." },
      { heading: "5. A way to contact you", text: "A phone number that dials when tapped, and a short form. Both." },
      { heading: "6. Photos", text: "The set you gathered in Module 2." },
      { heading: "7. Hours", text: "The same hours you'll put on Google." },
      { heading: "8. The boring bits", text: "A page title, a padlock (HTTPS), and it has to work on a phone. These are where DIY sites usually go wrong." },
    ],
    troubleshooting: [],
    mistakes: [
      "Building five pages when one would do. More pages means more to keep accurate.",
      "Leading with your story instead of what you do and where.",
    ],
    alternatives: [],
    canonicalFields: [],
    reusesFields: ["services", "serviceAreas", "phone", "email"],
    serviceOffer: "task_3_1",
    verifyVariant: {
      title: "Check your existing website has the essentials",
      intro: "You said you already have a website. Check it against the eight essentials:",
      checks: [
        "Does the headline say what you do and where?",
        "Does the phone number dial when tapped on a phone?",
        "Is there a contact form, and does it actually send?",
        "Does it show a padlock in the browser (HTTPS)?",
        "Is it readable on a phone without zooming?",
      ],
    },
    dependsOn: [],
    sourceLinks: [],
    lastReviewed: "2026-09-13",
    contentStatus: "complete",
  },
  {
    id: "3.2",
    moduleId: "website",
    title: "Write your website copy",
    order: 2,
    isRequired: true,
    timeEstimate: "15 minutes",
    whyItMatters:
      "The blank page is where most DIY websites die. You've already told us what you do, who for, and where — so we'll draft the words. You edit, you keep what sounds like you.",
    whatYouNeed: ["Your services and service area (we have them).", "Five minutes to answer two or three questions we don't know yet."],
    doThis:
      "Open the Website Copy Builder. It already knows your business — it will only ask what it doesn't. You'll get a headline, a subheadline, a short blurb for each service, an About paragraph, and a call to action. Edit anything that doesn't sound like you, then save.",
    primaryCta: { label: "Open the Website Copy Builder", toolId: "website_copy" },
    steps: [
      { text: "Answer the remaining questions — usually just \"why should someone choose you\" and \"what should a visitor do next.\"" },
      { text: "Read the draft out loud. Cut anything you wouldn't say to a customer's face." },
      { text: "Check every fact. The builder only uses what you've told us, but you're the one publishing it." },
      { text: "Save it. It's stored in Your Business so you can copy it into whatever you build." },
    ],
    troubleshooting: [
      { heading: "It sounds too polished", text: "Make it shorter and plainer. Short, specific sentences beat smooth ones for local trades." },
    ],
    mistakes: [
      "Adding claims the builder didn't make — \"licensed and insured,\" \"20 years experience\" — unless they're true and you've told us.",
      "Keeping everything. Cut a third.",
    ],
    alternatives: [],
    canonicalFields: ["longDescription"],
    reusesFields: ["displayName", "services", "serviceAreas", "idealCustomer", "differentiators"],
    toolId: "website_copy",
    dependsOn: ["1.3"],
    sourceLinks: [],
    lastReviewed: "2026-09-13",
    contentStatus: "complete",
  },
  {
    id: "3.3",
    moduleId: "website",
    title: "Build your website",
    order: 3,
    isRequired: true,
    timeEstimate: "20–30 minutes",
    whyItMatters:
      "You've already given us everything a one-page site needs. The builder turns it into a real website you can see on your phone and desktop, change by hand as much as you like, and approve when it's right.",
    whatYouNeed: ["Nothing new. It starts from what's already in Your Business.", "A few taps to choose a look, and your logo or a photo if you have one."],
    doThis:
      "Open the builder. Pick a style, colours, and what visitors should do first. Tap Build my website, then read every line — change anything by hand for free, or ask for a fresh take on one section. When it's true and sounds like you, approve it. You'll choose how to host it after that, not before.",
    primaryCta: { label: "Open the website builder", href: "/site" },
    steps: [
      { heading: "Check what we know", text: "The first screen shows every fact the site will use. If something's wrong, fix it in Your Business — it updates everywhere." },
      { heading: "Choose the look", text: "Six styles, a few colour sets, your logo or a clean text logo. There are no wrong answers; you can change them later without using anything up." },
      { heading: "Build, then read it aloud", text: "Cut anything you wouldn't say to a customer's face. Editing by hand never runs out." },
      { heading: "Approve", text: "You'll confirm each public detail — phone, email, hours, areas — before anything can go live." },
    ],
    troubleshooting: [
      { heading: "It says a detail is missing", text: "The builder won't invent facts. Add the missing detail in Your Business and come back." },
      { heading: "I'd rather not do this at all", text: "That's fine. Have GoBeeFound build it for you for $900, with what you paid for Launch taken off. The option is on the builder's first screen." },
    ],
    mistakes: [
      "Approving without reading every line. You're the one publishing it.",
      "Adding claims by hand — \"licensed and insured,\" \"20 years\" — unless they're true. The approval check will ask you to remove anything you haven't told us.",
    ],
    alternatives: [],
    canonicalFields: [],
    reusesFields: ["displayName", "services", "serviceAreas", "phone", "email", "hours"],
    serviceOffer: "builder_entry",
    verifyVariant: {
      title: "Check who controls your website",
      intro: "You have a website already. Confirm:",
      checks: [
        "You can log in to wherever it's hosted and change the text yourself.",
        "You know what it costs per month and when it renews.",
        "If someone else built it, you have the login — not just their phone number.",
      ],
    },
    dependsOn: ["3.1"],
    sourceLinks: [],
    lastReviewed: "2026-09-14",
    contentStatus: "complete",
  },
  {
    id: "3.4",
    moduleId: "website",
    title: "Point your domain at your site",
    order: 4,
    isRequired: true,
    timeEstimate: "10 minutes · then up to a few hours to take effect",
    whyItMatters:
      "Right now your domain and your website are two separate things. This step connects them so yourbusiness.com actually opens your site. It's the fiddliest step in the whole plan — and it's two lines of copy-and-paste.",
    whatYouNeed: ["Your Porkbun login.", "The DNS values your website builder gives you (it will show them on a \"connect your domain\" screen)."],
    doThis:
      "In your website builder, find \"connect a domain\" and enter your domain. It will show you one or two records to add. Open your domain at Porkbun, go to DNS, and add exactly those records. Then wait — it can take minutes or a few hours. When yourbusiness.com opens your site with a padlock, you're done.",
    primaryCta: { label: "Open Porkbun DNS", href: "https://porkbun.com/account/domainsSpeedy" },
    steps: [
      { heading: "What the two records do", text: "An \"A record\" points your bare domain (yourbusiness.com) at your site's address. A \"CNAME\" points www.yourbusiness.com at it too. Your builder tells you the exact values; you don't have to understand them, just copy them." },
      { heading: "At Porkbun", text: "Open your domain, choose DNS records, and add each record your builder listed — type, host, and answer, exactly as shown. Delete any old A or CNAME records for the same host that Porkbun added by default, or they'll fight." },
      { heading: "Waiting", text: "Changes usually show within minutes, sometimes a few hours. Your builder's connect screen will turn green when it sees them. Mark this step \"waiting\" and we'll move you on to something else meanwhile." },
      { heading: "Confirm", text: "Open yourbusiness.com on your phone. You should see your site and a padlock. If yes, you're done." },
    ],
    troubleshooting: [
      { heading: "Still not working after a few hours", text: "Nine times out of ten it's a leftover default record at Porkbun. Delete any A or CNAME record for @ or www that you didn't add yourself, and keep only the ones your builder gave you." },
      { heading: "No padlock", text: "Your builder issues the certificate automatically once the domain connects, usually within an hour. If it's been longer, look for an \"SSL\" or \"secure\" toggle in the builder's domain settings." },
      { heading: "This is the step people get stuck on", text: "If you've tried twice and it isn't working, stop. Send us your details and we'll point it for you — it takes us fifteen minutes." },
    ],
    mistakes: [
      "Typing the records instead of copying them. One wrong character and nothing works.",
      "Changing the nameservers when the builder only asked for records. Don't touch nameservers unless the builder explicitly says to.",
    ],
    alternatives: [
      { heading: "My domain is at a different registrar", text: "The records are identical; only the screen looks different. Every registrar has a \"DNS\" or \"DNS records\" page for each domain. Your registrar's help site will have a guide called something like \"add an A record.\"" },
    ],
    canonicalFields: [],
    reusesFields: ["domain"],
    supportsAwaitingVerification: true,
    verifyVariant: {
      title: "Check your domain is connected",
      intro: "You have a website already. Confirm:",
      checks: [
        "yourbusiness.com opens your site — not a parking page, not a builder subdomain.",
        "www.yourbusiness.com opens it too.",
        "There's a padlock in the address bar.",
      ],
    },
    dependsOn: ["2.2", "3.3"],
    sourceLinks: [{ label: "Porkbun — How to edit DNS records", href: "https://kb.porkbun.com/article/68-how-to-edit-dns-records" }],
    lastReviewed: "2026-09-13",
    contentStatus: "draft",
  },
  {
    id: "3.5",
    moduleId: "website",
    title: "Check your site works, and save the link",
    order: 5,
    isRequired: true,
    timeEstimate: "5 minutes",
    whyItMatters:
      "A site that looks fine on your laptop can be unusable on a customer's phone. Two minutes of checking now saves the customer who gives up and calls someone else.",
    whatYouNeed: ["Your phone.", "The details below to check against."],
    doThis:
      "Open your site on your phone — not your laptop. Tap the phone number: it should start a call. Fill out the contact form with your own details and submit it: the message should reach you. Check for the padlock. Read it without zooming. Then save your website address below.",
    primaryCta: { label: "Save your website link below" },
    steps: [
      { text: "Tap the phone number. Does your phone offer to call it? Is it the right number?" },
      { text: "Submit the contact form to yourself. Did it arrive? At the right email?" },
      { text: "Is there a padlock next to the address?" },
      { text: "Can you read everything without pinching to zoom? Are buttons big enough to tap?" },
      { text: "Do the hours and service area match what you told us?" },
    ],
    troubleshooting: [
      { heading: "The form didn't arrive", text: "Check spam first. Then check the form's \"send to\" address in your builder — it often defaults to the account email, not your business email." },
    ],
    mistakes: ["Only checking on a computer. Most of your visitors are on a phone."],
    alternatives: [],
    canonicalFields: [],
    reusesFields: ["phone", "email", "domain", "hours", "serviceAreas"],
    createsAsset: "website",
    dependsOn: ["3.4"],
    sourceLinks: [],
    lastReviewed: "2026-09-13",
    contentStatus: "complete",
  },
  {
    id: "3.6",
    moduleId: "website",
    title: "Set your page title and description",
    order: 6,
    isRequired: true,
    timeEstimate: "10 minutes",
    whyItMatters:
      "The page title is what shows in the browser tab and in Google's results. Most DIY sites leave it as \"Home\" — which tells nobody anything.",
    whatYouNeed: ["Your website builder login.", "Nothing else — the tool already knows your name, services, and area."],
    doThis:
      "Open Page Title & Description. It drafts a title (your business name, what you do, and where — under about 60 characters) and a one-sentence description (under about 155), sized to fit. Edit, save, then paste both into your builder's page settings, usually under \"SEO\" or \"page settings.\"",
    primaryCta: { label: "Open Page Title & Description", toolId: "seo_meta" },
    steps: [
      { text: "Title: \"Dave's Aurora Detail — Mobile Car Detailing in Aurora, CO\". Name, what, where. Nothing else." },
      { text: "Description: one plain sentence saying what you do and where. It's what shows under your name in Google results — your phone number goes on the page itself, not here." },
      { text: "In your builder, find the home page's settings — often labelled SEO, page settings, or metadata — and paste both in." },
    ],
    troubleshooting: [],
    mistakes: [
      "Stuffing the title with every service and city. It gets cut off and looks spammy.",
      "Leaving it as \"Home\" or \"Untitled.\"",
    ],
    alternatives: [],
    canonicalFields: ["pageTitle", "metaDescription"],
    reusesFields: ["displayName", "serviceAreas", "services"],
    toolId: "seo_meta",
    dependsOn: ["3.5"],
    sourceLinks: [],
    lastReviewed: "2026-09-13",
    contentStatus: "complete",
  },
];
